// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NSAS_PROJECT.Web.Data;
using System;

namespace NSAS_PROJECT.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NSAS_PROJECT.Core.Features.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dateregistered");

                    b.Property<string>("Email")
                        .HasMaxLength(64);

                    b.Property<string>("Fullname");

                    b.Property<string>("Gender");

                    b.Property<int>("Phonenumber");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NSAS_PROJECT.Core.Features.Users.User", b =>
                {
                    b.OwnsOne("NSAS_PROJECT.Core.Features.Shared.Address", "Address", b1 =>
                        {
                            b1.Property<int>("UserId");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(64);

                            b1.Property<string>("Addressline1")
                                .HasMaxLength(64);

                            b1.Property<string>("City")
                                .HasMaxLength(64);

                            b1.Property<string>("State")
                                .HasMaxLength(2);

                            b1.Property<int>("ZipCode")
                                .HasMaxLength(5);

                            b1.ToTable("User");

                            b1.HasOne("NSAS_PROJECT.Core.Features.Users.User")
                                .WithOne("Address")
                                .HasForeignKey("NSAS_PROJECT.Core.Features.Shared.Address", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
